PhET widget: remove simpleValidate (#1578)
## Summary:
Remove `simpleValidate()` from the PhET widget because it is a non-answerable widget.
* Because widgets without a `simpleValidate()` are handled correctly by our grading infrastructure (they are simply not graded), as per Jeremy's suggestion, we will remove the function from PhET!
* Also resolves `TypeError: JE.validate is not a function` error on PhET simulation content

Issue: LEMS-2287

## Test plan:
* `yarn jest packages/perseus/src/widgets/__tests__/phet-simulation.test.ts`
* `yarn jest packages/perseus-editor/src/widgets/__tests__/phet-simulation-editor.test.tsx`
* Verify that the widget and editor still show up in Storybook
* Verify that the widget shows up and remains ungraded on [Test Everything](https://www.khanacademy.org/internal-courses/test-everything/test-everything-1/x6df8cbb5b9ebc9c6:phet-simulation/e/projectile-data-lab)

Author: aemandine

Reviewers: jeremywiebe

Required Reviewers:

Approved By: jeremywiebe

Checks: ✅ codecov/project, ✅ codecov/patch, ✅ Upload Coverage (ubuntu-latest, 20.x), ✅ Cypress (ubuntu-latest, 20.x), ✅ Publish npm snapshot (ubuntu-latest, 20.x), ✅ Jest Coverage (ubuntu-latest, 20.x), ✅ Check builds for changes in size (ubuntu-latest, 20.x), ✅ Check for .changeset entries for all changed files (ubuntu-latest, 20.x), ✅ Lint, Typecheck, Format, and Test (ubuntu-latest, 20.x), ✅ gerald, ⏭️  Upload Coverage, ✅ Publish npm snapshot (ubuntu-latest, 20.x), ❌ Jest Coverage (ubuntu-latest, 20.x), ✅ Check builds for changes in size (ubuntu-latest, 20.x), ✅ Cypress (ubuntu-latest, 20.x), ✅ Check for .changeset entries for all changed files (ubuntu-latest, 20.x), ❌ Lint, Typecheck, Format, and Test (ubuntu-latest, 20.x), ✅ Publish Storybook to Chromatic (ubuntu-latest, 20.x), ✅ gerald

Pull Request URL: https://github.com/Khan/perseus/pull/1578