Import addLibraryVersionToPerseusDebug from local file, not package (#762)
## Summary:

While implementing our production version diagnostics for Perseus, I used some shell scripts to generate out the code for each package. In doing so, I implemented the `version.ts` for `perseus-core` incorrectly (as that's the package that hosts the helper function). 

All tests pass locally but when Perseus is integrated into a host application, it blows up with the error: `TypeError: perseusCore.addLibraryVersionToPerseusDebug is not a function` (@nedredmond).

Issue: "none"

## Test plan:

`yarn test` 
Let the snapshot build and then try it in webapp.

Author: jeremywiebe

Reviewers: jeremywiebe, benchristel, nedredmond

Required Reviewers:

Approved By: benchristel, nedredmond

Checks: ⌛ Upload Coverage, ✅ Publish npm snapshot (ubuntu-latest, 16.x), ✅ Lint, Typecheck, Format, and Test (ubuntu-latest, 16.x), ✅ Extract i18n strings (ubuntu-latest, 16.x), ✅ Cypress (ubuntu-latest, 16.x), ✅ Jest Coverage (ubuntu-latest, 16.x), ✅ Check for .changeset entries for all changed files (ubuntu-latest, 16.x), ✅ Check builds for changes in size (ubuntu-latest, 16.x), ✅ Publish Storybook to Chromatic (ubuntu-latest, 16.x), ✅ gerald

Pull Request URL: https://github.com/Khan/perseus/pull/762