Revert "Refactor all remaining 'mixins' uses"
This reverts commit b0315b469bd0a0fedbbfe8aa9ddace01f2d14034.

SAT passages are broken now :( passage-ref shows "?" instead of proper line numbers, and I see the following two errors in the JS console:

```
perseus-slim.js:7601 Uncaught TypeError: this.getUserInput is not a function(…)
perseus-extras.js:7639 Uncaught TypeError: Cannot read property 'measureLineHeight' of null(…)
```

Auditors: kevinb, emily