Pin node version for CI to 24.16.0 (#3838)
## Summary:
We think this will fix the intermittent issues we've been seeing where Changesets can't
call the GitHub API.

The errors look like this:
```
The following error was encountered while generating changelog entries
We have escaped applying the changesets, and no files should have been affected
🦋  error Error: Failed to parse data from GitHub
🦋  error Invalid response body while trying to fetch https://api.github.com/graphql: Premature close
🦋  error     at /home/runner/work/perseus/perseus/node_modules/.pnpm/@changesets+get-github-info@0.8.0_encoding@0.1.13/node_modules/@changesets/get-github-info/dist/changesets-get-github-info.cjs.js:185:11
🦋  error     at process.processTicksAndRejections (node:internal/process/task_queues:104:5)
Error: Process completed with exit code 1.
```

Context: https://khanacademy.slack.com/archives/C01AZ9H8TTQ/p1782749103893839?thread_ts=1782748411.810039&cid=C01AZ9H8TTQ

Issue: none

## Test plan:

CI should publish a dev build successfully.

Author: benchristel

Reviewers: somewhatabstract, Myranae, jeremywiebe

Required Reviewers:

Approved By: somewhatabstract, Myranae

Checks: ⏭️  1 check has been skipped, ✅ 12 checks were successful

Pull Request URL: https://github.com/Khan/perseus/pull/3838