[Definition] Fix typo in translation (#3727)
## Summary:
[Definition] Fix typo in translation

This will fix the CI issue in frontend
```
@khan/classroom-builders:typecheck
cache miss, executing 4e7062bac8b2b037

> @khan/classroom-builders@0.0.1 typecheck /home/github/work/frontend/frontend/libs/classroom/builders
> tsc --noEmit

Error: ../../component/perseus/src/perseus-strings-lingui.tsx(579,5): error TS2322: Type 'string' is not assignable to type '({ word }: { word: string; }) => string'.
```

Issue: LEMS-4104

## Test plan:

Author: ivyolamit

Reviewers: jeremywiebe

Required Reviewers:

Approved By: jeremywiebe

Checks: ✅ 12 checks were successful, ⏭️  3 checks have been skipped

Pull Request URL: https://github.com/Khan/perseus/pull/3727