Disable terser rollup plugin (#228)
## Summary:
The terser() plugin produces a bundle for @khanacademy/perseus-editor that webapp's webpack has trouble loading correctly.  While the build completes, when a page is loaded the imports this package, it failes with: 'TypeError: Object(...) is not a function'.

Disabling terser() fixes the issue.  I've created FEI-4557 to attempt to fix this in the future, possibly by upgrading to webpack 5 or tweaking the terser() config.

NOTE: The other packages that we publish do not appear to be affected by this issue.

Issue: None

## Test plan:
- yarn build
- copy dist/ folder for perseus-editor over to webapp's static service
- in webapp delete genwebpack/.cache-loader
- restart the dev server
- load http://localhost:8088/devadmin/content/exercises/evaluating_expressions_1/47765362/xf536eb63390a6371, see that it loads without issue

Author: kevinbarabash

Reviewers: jeremywiebe

Required Reviewers:

Approved By: jeremywiebe

Checks: ✅ codecov/project, ✅ Test Coverage (ubuntu-latest, 16.x), ✅ Check builds for changes in size (ubuntu-latest, 16.x), ✅ Lint, Flow, and Test (ubuntu-latest, 16.x), ✅ Extract i18n strings (ubuntu-latest, 16.x), ✅ gerald

Pull Request URL: https://github.com/Khan/perseus/pull/228