Fix types in test for perseus-linter (#1811)
While working on something else, I saw TypeScript errors coming from this file.
The error was:

```
packages/perseus-linter/src/__tests__/rule.test.ts:83:32 - error TS2339: Property 'check' does not exist on type 'never'.

83                 const lint = r.check(node, state, content);
```

I'm not sure why this just started erroring, but the types are definitely *weird*, so I'm
taking the opportunity to fix them.

There was also a test that depended on a previous test having been run. I fixed
that too.

Issue: none

## Test plan:

`yarn test`

Author: benchristel

Reviewers: mark-fitzgerald, benchristel, handeyeco, jeremywiebe

Required Reviewers:

Approved By: mark-fitzgerald

Checks: ✅ Publish npm snapshot (ubuntu-latest, 20.x), ✅ Lint, Typecheck, Format, and Test (ubuntu-latest, 20.x), ✅ Check builds for changes in size (ubuntu-latest, 20.x), ✅ Cypress (ubuntu-latest, 20.x), ✅ Check for .changeset entries for all changed files (ubuntu-latest, 20.x), ✅ Publish Storybook to Chromatic (ubuntu-latest, 20.x), ✅ gerald

Pull Request URL: https://github.com/Khan/perseus/pull/1811