[Radio] | (DX) | Add null check in radio.ff.tsx (#2742)
## Summary:
The preview in storybook was broken because of the following error
```
TypeError: Cannot read properties of undefined (reading 'choicesSelected')
```

Fixing that here.

| Before | After |
| --- | --- |
| <img width="492" height="601" alt="Screenshot 2025-07-25 at 3 19 52 PM" src="https://github.com/user-attachments/assets/cbffc071-1419-4cd3-ba22-d783dc266caa" /> | <img width="476" height="827" alt="Screenshot 2025-07-25 at 3 20 04 PM" src="https://github.com/user-attachments/assets/b13f506e-8e8f-44cb-9219-52114c606339" /> |


Issue: none

## Test plan:
- Go to http://localhost:6006/?path=/docs/widgets-radio-editor-demo--docs#multi-choice
- Confirm that the preview shows the Radio widget
- Confirm that the browser console has no errors

Author: nishasy

Reviewers: mark-fitzgerald, ivyolamit, handeyeco, SonicScrewdriver, anakaren-rojas

Required Reviewers:

Approved By: mark-fitzgerald, ivyolamit, handeyeco

Checks: ✅ 14 checks were successful, ⏹️  3 checks were cancelled

Pull Request URL: https://github.com/Khan/perseus/pull/2742