[radio-storybook-preview-fix] [Radio] | (DX) | Fix storybook preview
The preview in storybook was broken because of the following error
```
TypeError: Cannot read properties of undefined (reading 'choicesSelected')
```

Fixing that here.

Issue: none

Test plan:
- Go to http://localhost:6006/?path=/docs/widgets-radio-editor-demo--docs#multi-choice
- Confirm that the preview shows the Radio widget
- Confirm that the browser console has no errors