Exclude package dist dirs from type builds (#4190)
## Summary:

The `exclude` entry for `dist` dirs was incorrect in `tsconfig-shared.json`. Relative paths in any TS config file are relative to _that_ file, not any file that `extends` it. So we were effectively excluding `packages/dist/` instead of `packages/<package>/dist/`. 

This also caused an error if you ran `pnpm build:types` twice in a row:

```
error TS5055: Cannot write file '/Users/jeremy/khan/perseus/packages/math-input/dist/index.d.ts' because it would overwrite input file.
```

This was because generating types tried to generate the (non-excluded) type file over itself. 

Issue: LEMS-4571 

## Test plan:

`pnpm clean; pnpm build:types; pnpm build:types` (succeeds and there are the correct `.d.ts` files in `packages/<package>/dist/`

Author: jeremywiebe

Reviewers: somewhatabstract, ivyolamit

Required Reviewers:

Approved By: somewhatabstract, ivyolamit

Checks: ⏭️  1 check has been skipped, ✅ 10 checks were successful

Pull Request URL: https://github.com/Khan/perseus/pull/4190