Fix 'Exempt snapshots' step of Chromatic build (#4231)
## Summary:

Nisha noted that the Version Packages PR was failing with the following error: 

```
 Error: ✖ Build script not found
             The CLI didn't find a script called "build-storybook" in your package.json.
             Make sure you set the --build-script-name option to the value of the script name that builds your Storybook.
```

Apparently, even though we pass `skip: true` to the `chromaui/action` Github Action, it still performs config validation and fails. We build storybook separately if needed so that's why we don't et the 

Issue: LEMS-4608 

## Test plan:

Author: jeremywiebe

Reviewers: jeremywiebe, nishasy

Required Reviewers:

Approved By: nishasy

Checks: ⏭️  2 checks have been skipped, ✅ 11 checks were successful

Pull Request URL: https://github.com/Khan/perseus/pull/4231